insert into station (name, address, price) values ('Hooker', '92262 Hudson Plaza', 8.37);
insert into station (name, address, price) values ('Garrison', '038 Norway Maple Place', 19.89);
insert into station (name, address, price) values ('Lillian', '1647 Di Loreto Avenue', 67.67);
insert into station (name, address, price) values ('Delladonna', '9 Lakeland Parkway', 30.46);
insert into station (name, address, price) values ('Prairie Rose', '205 Carey Hill', 63.95);
insert into station (name, address, price) values ('Longview', '4600 Hansons Road', 4.94);
insert into station (name, address, price) values ('Homewood', '4820 School Parkway', 95.07);
insert into station (name, address, price) values ('American Ash', '3254 Service Hill', 39.38);
insert into station (name, address, price) values ('Sunfield', '3281 Schiller Plaza', 52.57);
insert into station (name, address, price) values ('Green', '8 Clemons Trail', 69.94);
insert into station (name, address, price) values ('Roxbury', '2 Victoria Trail', 64.34);
insert into station (name, address, price) values ('Transport', '1 Crownhardt Park', 77.43);
insert into station (name, address, price) values ('Shasta', '936 7th Crossing', 11.99);
insert into station (name, address, price) values ('Eastwood', '6 Del Mar Pass', 27.39);
insert into station (name, address, price) values ('Cherokee', '7 Myrtle Court', 33.03);
insert into station (name, address, price) values ('Monument', '29 Butternut Avenue', 56.77);
insert into station (name, address, price) values ('Mosinee', '296 Westridge Parkway', 68.15);
insert into station (name, address, price) values ('Scott', '5 Susan Way', 53.23);
insert into station (name, address, price) values ('Evergreen', '45918 Harbort Center', 94.32);
insert into station (name, address, price) values ('Chive', '3631 Dorton Drive', 42.87);
insert into station (name, address, price) values ('Homewood', '9694 Laurel Terrace', 19.79);
insert into station (name, address, price) values ('Main', '26976 Dayton Terrace', 18.81);
insert into station (name, address, price) values ('Thompson', '3 Briar Crest Court', 8.54);
insert into station (name, address, price) values ('Fieldstone', '17630 Debra Drive', 98.87);
insert into station (name, address, price) values ('Warrior', '938 Northwestern Way', 51.72);
insert into station (name, address, price) values ('Prairie Rose', '5105 Michigan Road', 95.07);
insert into station (name, address, price) values ('Barnett', '37227 Elmside Point', 44.04);
insert into station (name, address, price) values ('Blue Bill Park', '73129 Reinke Crossing', 85.29);
insert into station (name, address, price) values ('Schlimgen', '53 Merry Terrace', 85.24);
insert into station (name, address, price) values ('Anthes', '404 Center Circle', 24.97);
insert into station (name, address, price) values ('Lukken', '0 Pleasure Avenue', 92.81);
insert into station (name, address, price) values ('Hermina', '56 Arapahoe Circle', 37.57);
insert into station (name, address, price) values ('Acker', '9985 Trailsway Place', 26.49);
insert into station (name, address, price) values ('Delaware', '4910 Daystar Point', 47.6);
insert into station (name, address, price) values ('Weeping Birch', '65 Vermont Crossing', 51.73);
insert into station (name, address, price) values ('Russell', '39215 Miller Way', 37.0);
insert into station (name, address, price) values ('Banding', '0 Crest Line Crossing', 84.22);
insert into station (name, address, price) values ('Tony', '514 Blackbird Plaza', 74.11);
insert into station (name, address, price) values ('Cherokee', '8215 Crowley Place', 72.21);
insert into station (name, address, price) values ('Briar Crest', '58491 Cascade Way', 45.07);
insert into station (name, address, price) values ('Clemons', '42537 Farmco Pass', 4.48);
insert into station (name, address, price) values ('Mifflin', '35583 Randy Trail', 27.12);
insert into station (name, address, price) values ('Talisman', '30 Menomonie Trail', 57.69);
insert into station (name, address, price) values ('Melvin', '49 Vermont Point', 13.34);
insert into station (name, address, price) values ('Oak', '46 Marquette Street', 42.56);
insert into station (name, address, price) values ('Kings', '95964 Talmadge Hill', 53.62);
insert into station (name, address, price) values ('Knutson', '61458 Blaine Crossing', 56.51);
insert into station (name, address, price) values ('Oriole', '92 Mallory Road', 33.33);
insert into station (name, address, price) values ('Eliot', '2 Acker Avenue', 52.51);
insert into station (name, address, price) values ('Esker', '103 Thackeray Drive', 41.59);
insert into station (name, address, price) values ('Dovetail', '7393 David Pass', 90.42);
insert into station (name, address, price) values ('Sunfield', '71803 Browning Street', 74.65);
insert into station (name, address, price) values ('Mccormick', '40635 Dixon Hill', 85.84);
insert into station (name, address, price) values ('Banding', '427 Schlimgen Lane', 6.71);
insert into station (name, address, price) values ('Buena Vista', '185 Ronald Regan Court', 51.1);
insert into station (name, address, price) values ('Messerschmidt', '157 Maywood Point', 55.98);
insert into station (name, address, price) values ('Pepper Wood', '15 Farwell Avenue', 47.66);
insert into station (name, address, price) values ('Hintze', '34857 Gale Terrace', 82.66);
insert into station (name, address, price) values ('Ridge Oak', '5457 Artisan Hill', 16.22);
insert into station (name, address, price) values ('Shopko', '453 Brentwood Park', 81.26);
insert into station (name, address, price) values ('Superior', '7068 Calypso Terrace', 7.17);
insert into station (name, address, price) values ('Crest Line', '83 2nd Drive', 9.93);
insert into station (name, address, price) values ('Bartillon', '96 Manley Hill', 40.0);
insert into station (name, address, price) values ('Sunfield', '47 Bashford Parkway', 56.18);
insert into station (name, address, price) values ('Erie', '76 Eastwood Way', 73.35);
insert into station (name, address, price) values ('Brown', '64 Hallows Pass', 95.44);
insert into station (name, address, price) values ('Golf View', '188 Atwood Hill', 9.17);
insert into station (name, address, price) values ('Derek', '12 Harper Way', 55.19);
insert into station (name, address, price) values ('Riverside', '102 Dovetail Junction', 28.07);
insert into station (name, address, price) values ('Comanche', '56103 Iowa Trail', 84.94);
insert into station (name, address, price) values ('Granby', '7157 Dayton Center', 95.72);
insert into station (name, address, price) values ('Clemons', '24 Mayer Circle', 94.93);
insert into station (name, address, price) values ('Reinke', '9 Duke Drive', 81.32);
insert into station (name, address, price) values ('Aberg', '5771 Bellgrove Way', 76.12);
insert into station (name, address, price) values ('Old Gate', '8 Leroy Crossing', 49.73);
insert into station (name, address, price) values ('Del Mar', '9 Toban Crossing', 59.44);
insert into station (name, address, price) values ('Holy Cross', '92133 Duke Street', 61.12);
insert into station (name, address, price) values ('International', '5 Farragut Point', 94.63);
insert into station (name, address, price) values ('Bonner', '6 Golf Course Street', 77.43);
insert into station (name, address, price) values ('Badeau', '1 Portage Lane', 73.25);
insert into station (name, address, price) values ('Washington', '23397 New Castle Plaza', 58.26);
insert into station (name, address, price) values ('Harper', '8 Menomonie Circle', 6.13);
insert into station (name, address, price) values ('Dixon', '89321 Oriole Junction', 80.13);
insert into station (name, address, price) values ('Crowley', '7447 Graceland Hill', 36.5);
insert into station (name, address, price) values ('Mitchell', '6019 Northridge Trail', 60.25);
insert into station (name, address, price) values ('Eastlawn', '720 Kinsman Plaza', 26.27);
insert into station (name, address, price) values ('Mockingbird', '19 Arapahoe Court', 71.41);
insert into station (name, address, price) values ('Summit', '5656 Morningstar Park', 80.26);
insert into station (name, address, price) values ('Melrose', '86 Lotheville Junction', 77.71);
insert into station (name, address, price) values ('Red Cloud', '81 Dapin Hill', 28.03);
insert into station (name, address, price) values ('Washington', '7 Morningstar Street', 81.13);
insert into station (name, address, price) values ('Victoria', '804 Troy Center', 72.58);
insert into station (name, address, price) values ('Logan', '16 Chive Avenue', 12.86);
insert into station (name, address, price) values ('Leroy', '44 Johnson Terrace', 30.0);
insert into station (name, address, price) values ('Sugar', '5 Jana Crossing', 36.89);
insert into station (name, address, price) values ('Spenser', '0 Green Parkway', 62.15);
insert into station (name, address, price) values ('Anderson', '6 Kingsford Alley', 28.51);
insert into station (name, address, price) values ('New Castle', '0493 Continental Avenue', 15.51);
insert into station (name, address, price) values ('Warbler', '22 Artisan Street', 91.95);
insert into station (name, address, price) values ('Waywood', '582 Pine View Place', 65.43);